
processing_config:
  parallellize_runs: False
  workers: 10

data_preprocessing_config:
  run_per_speaker: False
  persist_per_speaker_transcripts: False
  per_speaker_transcript_file_path: './generated_data/per_speaker_transcripts/'

summarization:
  model_name: 'human_centered_pegasus'
  max_length: 512
  truncate: True
  padding: True
  return_tensors: 'pt'
  generation_min_length: 10
  generation_max_length: 512
  skip_special_tokens: True

sentiment_analysis:
